name: Run Github Action Pipeline
on :
   push: 
       branches:
            -main

jobs:
   demo-job:
       runs-on: ubuntu_latest
       steps:
          -name: checkout-code
          uses: actions/checkout@v2 

          -name: print message
          runs: echo "Welcome to Github Actions"